services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes: 
      - ${CONFIG_ROOT:?}/heimdall:/config
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - internal-containers

  cross-seed:
    container_name: cross-seed
    image: crossseed/cross-seed:master
    user: 1000:1000
    environment:
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_ROOT:?}/cross-seed6:/config
      - ${CONFIG_ROOT:?}/ruTorrent/rtorrent/.session:/torrents:ro
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds
      - ${TORRENT_DATA:?}:/downloads
    expose:
      - "2468"
    command: daemon
    restart: unless-stopped
    networks:
      - internal-containers

  omegabrr:
    container_name: omegabrr
    image: ghcr.io/autobrr/omegabrr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    expose:
      - "7441"
    volumes:
      - ${CONFIG_ROOT:?}/omegabrr:/config
    networks:
      - internal-containers
      
  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes: 
      - ${CONFIG_ROOT:?}/unpackerr:/config
      - ${TORRENT_DATA:?}:/downloads
    networks:
      - internal-containers

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${CONFIG_ROOT:?}/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - internal-containers

  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr
    hostname: ssmedia.me
    volumes:
      - ${CONFIG_ROOT:?}/notifiarr:/config
    restart: unless-stopped
    networks:
      - internal-containers
    

volumes:
  netdatalib:
  netdatacache:
