services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes: 
      - ${CONFIG_ROOT:?}/heimdall:/config
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - internal-containers

  cross-seed:
    container_name: cross-seed
    image: crossseed/cross-seed
    volumes:
      - ${CONFIG_ROOT:?}/cross-seed:/config
      - ${CONFIG_ROOT:?}/qbittorrent/qBittorrent/BT_backup:/torrents:ro
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds
      - ${TORRENT_DATA:?}:/downloads
    expose:
      - "2468"
    command: daemon
    restart: unless-stopped
    networks:
      - internal-containers

  omegabrr:
    container_name: omegabrr
    image: ghcr.io/autobrr/omegabrr:latest
    expose:
      - "7441"
    volumes:
      - ${CONFIG_ROOT:?}/omegabrr:/config
    networks:
      - internal-containers

  qbit_manage:
    container_name: qbit_manage
    image: bobokun/qbit_manage
    environment:
      - QBT_SCHEDULE=10
    volumes:
      - ${CONFIG_ROOT:?}/qbitmanage:/config
    networks:
      - internal-containers

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${CONFIG_ROOT:?}/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - internal-containers

volumes:
  netdatalib:
  netdatacache:
