services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes: 
      - /home/docker/heimdall:/config
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - internal-containers

  rutorrent:
    container_name: rutorrent
    image: horjulf/rutorrent-autodl:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    ports:
      - "5000:5000"
      - "51413:51413"
      - "6881:6881/udp"
    expose:
      - "8080"
    volumes:
      - /home/docker/ruTorrent:/config
      - /data1/kingofzeal/torrentData:/downloads
      - /home/scripts:/scripts
    networks:
      - internal-containers
    restart: unless-stopped

  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    environment:
      - TZ=America/Chicago
    expose: 
      - "9091"
    volumes:
      - /home/docker/authelia:/config
    networks:
      - internal-containers
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: linuxserver/swag:latest
    depends_on:
      authelia:
        condition: service_started
        restart: false
    environment:
      - TZ=America/Chicago
      - URL=ssmedia.me
      - SUBDOMAINS=plex,radarr,sonarr,portainer,jackett,rutorrent,netdata,ombi,tautulli,requests,grafana,tdarr,prowlarr,authelia,heimdall,rutorrent2
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=30
      - ONLY_SUBDOMAINS=false
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/docker/nginx:/config
    networks:
      - internal-containers
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: curl localhost:80/health-check || exit 1
      interval: 60s
      timeout: 3s
    restart: unless-stopped

  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex
    environment:
      - PUID=130
      - PGID=135
      - VERSION=latest
    ports:
      - "32400:32400"
    volumes:
      - /var/lib/plexmediaserver:/config
      - /etc/letsencrypt/live/plex.ssmedia.me:/etc/letsencrypt/live/plex.ssmedia.me
      - rclone:/mnt/union
      - /data1/plex:/dev/shm
    healthcheck:
      test: ls /mnt/union || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks: 
      - internal-containers
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    environment:
      - TZ=America/Chicago
      - AUTO_UPDATE=true
      - PUID=1000
      - PGID=1000
    expose:
      - "9696"
    volumes:
      - /home/docker/prowlarr:/config
      - /mnt/union/Backup/Prowlarr:/config/Backups
    networks: 
      - internal-containers
    restart: unless-stopped

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/docker/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - internal-containers

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    depends_on:
      rutorrent:
        condition: service_started
        restart: false
      prowlarr:
        condition: service_started
        required: false
        restart: false
    environment:
      - TZ=America/Chicago
    expose:
      - "7878"
    volumes:
      - /home/docker/Radarr:/config
      - /mnt/union/Backup/Radarr:/config/Backups
      - /mnt/union/Movies:/mnt/union/Movies
      - /mnt/union/Recycle:/mnt/union/Recycle
      - /mnt/union/Temp:/mnt/union/Temp
      - /home/scripts:/scripts
      - /data1/kingofzeal/torrentData:/downloads
    healthcheck:
      test: ls /mnt/union/Movies || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      - internal-containers
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    depends_on:
      rutorrent:
        condition: service_started
        restart: false
      prowlarr:
        condition: service_started
        required: false
        restart: false
    environment:
      - TZ=America/Chicago
    expose:
      - "8989"
    volumes:
      - /home/docker/Sonarr:/config
      - /home/scripts:/scripts
      - /data1/kingofzeal/torrentData:/downloads
      - /mnt/union/Backup/Sonarr:/config/Backups
      - /mnt/union/TV:/mnt/union/TV
      - /mnt/union/Recycle:/mnt/union/Recycle
      - /mnt/union/Temp:/mnt/union/Temp
    healthcheck:
      test: ls /mnt/union/TV || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks: 
      - internal-containers
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    depends_on:
      sonarr:
        condition: service_healthy
        restart: false
      radarr:
        condition: service_healthy
        restart: false
      plex:
        condition: service_started
        required: false
        restart: false
    environment:
      - TZ=America/Chicago
    expose:
      - "3579"
    volumes:
      - /home/docker/overseerr:/app/config
    networks:
      - internal-containers
    restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    depends_on:
      plex:
        condition: service_started
        required: false
        restart: false
    environment: 
      - TZ=America/Chicago
    expose: 
      - "8181"
    volumes:
      - /home/docker/tautulli:/config
      - /mnt/union/Backup/Tautulli:/config/backups
      - "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/plex/Logs"
    networks: 
      - internal-containers
    restart: unless-stopped

volumes:
  netdatalib:
  netdatacache:
  rclone:
    driver: rclone
    driver_opts:
      remote: 'union:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

  rclone_TV:
    driver: rclone
    driver_opts:
      remote: 'union:TV'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

  rclone_Movies:
    driver: rclone
    driver_opts:
      remote: 'union:Movies'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

  rclone_Anime:
    driver: rclone
    driver_opts:
      remote: 'union:Anime'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

  rclone_Temp:
    driver: rclone
    driver_opts:
      remote: 'union:Temp'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

  rclone_Recycle:
    driver: rclone
    driver_opts:
      remote: 'union:Recycle'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
    
networks:
  internal-containers:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1

  hostbridge:
    external: true
    name: bridge