include:
  - auxiliary.yaml
  - media-acquisition.yaml
  - media-server.yaml
  - reverse-proxy.yaml

volumes:
  rclone: &rclone
    driver: rclone
    driver_opts: &rclone-opts
      remote: "union:"
      allow_other: "true"
      vfs_cache_mode: full
      poll_interval: 0

  rclone_TV: 
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:TV"

  rclone_Movies: 
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:Movies"

  rclone_Anime:
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:Anime"

  rclone_Temp: 
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:Temp"

  rclone_Recycle:
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:Recycle"

  rclone_eBooks:
    <<: *rclone
    driver_opts:
      <<: *rclone-opts
      remote: "union:eBooks"

networks:
  internal-containers:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1

  hostbridge:
    external: true
    name: bridge