services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${WINDSCRIBE_USERNAME:?}
      - OPENVPN_PASSWORD=${WINDSCRIBE_PASSWORD:?}
      - OPENVPN_CUSTOM_CONFIG=/gluetun/${WINDSCRIBE_OVPN_FILE:?}
      - VPN_ENDPOINT_IP=${WINDSCRIBE_ADDRESS:?}
      - VPN_ENDPOINT_PORT=${WINDSCRIBE_PORT:?}
      - FIREWALL_VPN_INPUT_PORTS=${WINDSCRIBE_FWD_PORT:?}
    volumes:
      - ${CONFIG_ROOT:?}/gluetun:/gluetun
    networks:
      - internal-containers
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - ${CONFIG_ROOT:?}/qbittorrent:/config
      - ${TORRENT_DATA:?}:/downloads
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds
    network_mode: service:gluetun
    restart: unless-stopped

  rutorrent:
    container_name: rutorrent
    image: lscr.io/linuxserver/rutorrent
    # ports:
    #   - "5000:5000"
    #   - "51413:51413"
    #   - "6881:6881/udp"
    # expose:
    #   - "80"
    volumes:
      - ${CONFIG_ROOT:?}/ruTorrent:/config
      - ${TORRENT_DATA:?}:/downloads
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds      
      - ${SCRIPTS_ROOT:?}:/scripts
    network_mode: service:gluetun
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    expose:
      - "7474"
    volumes:
      - ${CONFIG_ROOT:?}/autobrr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    networks:
      - internal-containers
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true
    expose:
      - "9696"
    volumes:
      - ${CONFIG_ROOT:?}/prowlarr:/config
      - ${BACKUP_ROOT:?}/Prowlarr:/config/Backups
    networks: 
      - internal-containers
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CROSS_SEED_HOST=${CROSS_SEED_HOST:?}
      - CROSS_SEED_API=${CROSS_SEED_API:?}
    expose:
      - "7878"
    volumes:
      - ${CONFIG_ROOT:?}/Radarr:/config
      - ${BACKUP_ROOT:?}/Radarr:/config/Backups
      - ${MEDIA_ROOT:?}/Movies:${MEDIA_ROOT:?}/Movies
      - ${MEDIA_ROOT:?}/Recycle:${MEDIA_ROOT:?}/Recycle
      - ${MEDIA_ROOT:?}/Temp:${MEDIA_ROOT:?}/Temp
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/Movies || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      - internal-containers
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CROSS_SEED_HOST=${CROSS_SEED_HOST:?}
      - CROSS_SEED_API=${CROSS_SEED_API:?}
    expose:
      - "8989"
    volumes:
      - ${CONFIG_ROOT:?}/Sonarr:/config
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
      - ${BACKUP_ROOT:?}/Sonarr:/config/Backups
      - ${MEDIA_ROOT:?}/Anime:${MEDIA_ROOT:?}/Anime
      - ${MEDIA_ROOT:?}/TV:${MEDIA_ROOT:?}/TV
      - ${MEDIA_ROOT:?}/Recycle:${MEDIA_ROOT:?}/Recycle
      - ${MEDIA_ROOT:?}/Temp:${MEDIA_ROOT:?}/Temp
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/TV || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks: 
      - internal-containers
    restart: unless-stopped
