services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    expose:
      - "3579"
    volumes:
      - ${CONFIG_ROOT:?}/overseerr:/app/config
    networks:
      - internal-containers
    restart: unless-stopped

  # tautulli:
  #   container_name: tautulli
  #   image: tautulli/tautulli:latest
  #   environment: 
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Chicago
  #   expose: 
  #     - "8181"
  #   volumes:
  #     - ${CONFIG_ROOT:?}/tautulli:/config
  #     - ${BACKUP_ROOT:?}/Tautulli:/config/backups
  #     # - "${CONFIG_ROOT:?}/Plex/Library/Application Support/Plex Media Server/Logs:/plex/Logs"
  #   networks: 
  #     - internal-containers
  #   restart: unless-stopped
