services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - ${CONFIG_ROOT:?}/qbittorrent:/config
      - ${TORRENT_DATA:?}:/downloads
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds      
    expose: 
      - "8080"
    ports:
      - "51414:51414"
      - "51414:51414/udp"
    networks:
      - internal-containers
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    expose:
      - "7474"
    volumes:
      - ${CONFIG_ROOT:?}/autobrr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    networks:
      - internal-containers
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true
      - PUID=1000
      - PGID=1000
    expose:
      - "9696"
    volumes:
      - ${CONFIG_ROOT:?}/prowlarr:/config
      - ${BACKUP_ROOT:?}/Prowlarr:/config/Backups
    networks: 
      - internal-containers
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CROSS_SEED_HOST=${CROSS_SEED_HOST:?}
      - CROSS_SEED_API=${CROSS_SEED_API:?}
    expose:
      - "7878"
    volumes:
      - ${CONFIG_ROOT:?}/Radarr:/config
      - ${BACKUP_ROOT:?}/Radarr:/config/Backups
      - rclone_Movies:${MEDIA_ROOT:?}/Movies
      - rclone_Recycle:${MEDIA_ROOT:?}/Recycle
      - rclone_Temp:${MEDIA_ROOT:?}/Temp
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/Movies || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      - internal-containers
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CROSS_SEED_HOST=${CROSS_SEED_HOST:?}
      - CROSS_SEED_API=${CROSS_SEED_API:?}
    expose:
      - "8989"
    volumes:
      - ${CONFIG_ROOT:?}/Sonarr:/config
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
      - ${BACKUP_ROOT:?}/Sonarr:/config/Backups
      - rclone_Anime:${MEDIA_ROOT:?}/Anime
      - rclone_TV:${MEDIA_ROOT:?}/TV
      - rclone_Recycle:${MEDIA_ROOT:?}/Recycle
      - rclone_Temp:${MEDIA_ROOT:?}/Temp
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/TV || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks: 
      - internal-containers
    restart: unless-stopped
