services:
  rutorrent:
    container_name: rutorrent
    image: horjulf/rutorrent-autodl:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    ports:
      - "5000:5000"
      - "51413:51413"
      - "6881:6881/udp"
    expose:
      - "8080"
    volumes:
      - ${CONFIG_ROOT:?}/ruTorrent:/config
      - ${TORRENT_DATA:?}:/downloads
      - ${SCRIPTS_ROOT:?}:/scripts
    networks:
      - internal-containers
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    depends_on:
      nginx:
        condition: service_healthy
        restart: false
    environment:
      - TZ=America/Chicago
      - AUTO_UPDATE=true
      - PUID=1000
      - PGID=1000
    expose:
      - "9696"
    volumes:
      - ${CONFIG_ROOT:?}/prowlarr:/config
      - ${BACKUP_ROOT:?}/Prowlarr:/config/Backups
    networks: 
      - internal-containers
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    depends_on:
      rutorrent:
        condition: service_started
        restart: false
      prowlarr:
        condition: service_started
        required: false
        restart: false
    environment:
      - TZ=America/Chicago
    expose:
      - "7878"
    volumes:
      - ${CONFIG_ROOT:?}/Radarr:/config
      - ${BACKUP_ROOT:?}/Radarr:/config/Backups
      - rclone_Movies:${MEDIA_ROOT:?}/Movies
      - rclone_Recycle:${MEDIA_ROOT:?}/Recycle
      - rclone_Temp:${MEDIA_ROOT:?}/Temp
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/Movies || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      - internal-containers
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    depends_on:
      rutorrent:
        condition: service_started
        restart: false
      prowlarr:
        condition: service_started
        required: false
        restart: false
    environment:
      - TZ=America/Chicago
    expose:
      - "8989"
    volumes:
      - ${CONFIG_ROOT:?}/Sonarr:/config
      - ${SCRIPTS_ROOT:?}:/scripts
      - ${TORRENT_DATA:?}:/downloads
      - ${BACKUP_ROOT:?}/Sonarr:/config/Backups
      - rclone_Anime:${MEDIA_ROOT:?}/Anime
      - rclone_TV:${MEDIA_ROOT:?}/TV
      - rclone_Recycle:${MEDIA_ROOT:?}/Recycle
      - rclone_Temp:${MEDIA_ROOT:?}/Temp
    healthcheck:
      test: ls ${MEDIA_ROOT:?}/TV || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s
    networks: 
      - internal-containers
    restart: unless-stopped
