services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${WINDSCRIBE_USERNAME:?}
      - OPENVPN_PASSWORD=${WINDSCRIBE_PASSWORD:?}
      - OPENVPN_CUSTOM_CONFIG=/gluetun/${WINDSCRIBE_OVPN_FILE:?}
      - VPN_ENDPOINT_IP=${WINDSCRIBE_ADDRESS:?}
      - VPN_ENDPOINT_PORT=${WINDSCRIBE_PORT:?}
      - FIREWALL_VPN_INPUT_PORTS=${WINDSCRIBE_FWD_PORT:?}
    volumes:
      - ${CONFIG_ROOT:?}/gluetun:/gluetun
    networks:
      - internal-containers
    restart: unless-stopped

  rutorrent:
    container_name: rutorrent
    image: crazymax/rtorrent-rutorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - XMLRPC_PORT=7441
      - RUTORRENT_PORT=80
      - RT_INC_PORT=43952
      - RT_LOG_XMLRPC=true
      - RT_LOG_EXECUTE=true
    # ports: # These are all exposed via the `gluetun` container
    #   - "5000:5000"
    #   - "51413:51413"
    #   - "6881:6881/udp"
    # expose:
    #   - "80"
    volumes:
      - ${CONFIG_ROOT:?}/ruTorrent:/data
      - ${TORRENT_DATA:?}:/downloads
      - ${TORRENT_DATA:?}/cross-seeds:/cross-seeds
      - ${SCRIPTS_ROOT:?}:/scripts
    network_mode: service:gluetun
    restart: unless-stopped