services:
    authelia:
      container_name: authelia
      image: authelia/authelia:latest
      environment:
        - TZ=America/Chicago
      expose: 
        - "9091"
      volumes:
        - ${CONFIG_ROOT:?}/authelia:/config
      networks:
        - internal-containers
      restart: unless-stopped
  
    nginx:
      container_name: nginx
      image: linuxserver/swag:latest
      environment:
        - TZ=America/Chicago
        - URL=ssmedia.me
        - SUBDOMAINS=wildcard
        - VALIDATION=dns
        - DNSPLUGIN=cloudflare
        - PROPAGATION=30
        - ONLY_SUBDOMAINS=false
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ${CONFIG_ROOT:?}/nginx:/config
      networks:
        internal-containers:
          ipv4_address: 172.18.1.1
      cap_add:
        - NET_ADMIN
      healthcheck:
        test: curl localhost:80/health-check || exit 1
        interval: 60s
        timeout: 3s
      restart: unless-stopped