services:
    authelia:
      container_name: authelia
      image: authelia/authelia:latest
      environment:
        - TZ=America/Chicago
      expose: 
        - "9091"
      volumes:
        - /home/docker/authelia:/config
      networks:
        - internal-containers
      restart: unless-stopped
  
    nginx:
      container_name: nginx
      image: linuxserver/swag:latest
      depends_on:
        authelia:
          condition: service_started
          restart: false
      environment:
        - TZ=America/Chicago
        - URL=ssmedia.me
        - SUBDOMAINS=plex,radarr,sonarr,portainer,jackett,rutorrent,netdata,ombi,tautulli,requests,grafana,tdarr,prowlarr,authelia,heimdall,rutorrent2
        - VALIDATION=dns
        - DNSPLUGIN=cloudflare
        - PROPAGATION=30
        - ONLY_SUBDOMAINS=false
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - /home/docker/nginx:/config
      networks:
        - internal-containers
      cap_add:
        - NET_ADMIN
      healthcheck:
        test: curl localhost:80/health-check || exit 1
        interval: 60s
        timeout: 3s
      restart: unless-stopped