docker network connect bridge sonarr 2> /dev/null
docker network connect bridge radarr 2> /dev/null
docker network connect bridge nginx 2> /dev/null
docker network connect bridge rutorrent 2> /dev/null
docker network connect bridge netdata 2> /dev/null
docker network connect bridge prowlarr 2> /dev/null
docker network connect bridge plex 2> /dev/null
docker network connect bridge heimdall 2> /dev/null
docker network connect bridge overseerr 2> /dev/null
docker network connect bridge tautulli 2> /dev/null
docker network connect bridge autobrr 2> /dev/null
docker network connect bridge qbittorrent 2> /dev/null
